services:
  backend:
    container_name: lab_backend
    build:
      context: ./app
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./app/requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    restart: always
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - fast_api
  
networks:
  fast_api:
    driver: bridge

